### PR TITLE
Fix CR apiversion and target namespace/name

### PR DESCRIPTION
**Pull request by ingvagabund**
CR is expected to live under `openshift-kube-descheduler-operator/cluster`.

### CODE REVIEW

**Comment by ingvagabund** [comment]
@mdame PTAL

**Comment by damemi** [comment]
/lgtm cancel
Something I noticed, the CR shouldn't be created until after at least the namespace. So Could you rename the cr to just `02_kube-descheduler-operator.cr.yaml`. This will let you deploy the whole operator with just `oc create -f manifests/.`

**Comment by damemi** [comment]
Picked into https://github.com/openshift/cluster-kube-descheduler-operator/pull/66, so I'm going to close this so we don't need to open another BZ
/close

**Pull request closed without merging**
