### PR TITLE
Rebase 1.18.0 beta.2

### PR DESCRIPTION
**Pull request by ingvagabund**
/hold

Things:
- `NewConfigObserver` method of `pkg/operator/configobservation/configobservercontroller/observe_config_controller.go` is not used anywhere. Should we remove it or call it?

### CODE REVIEW

**Comment by damemi** [comment]
Feel free to remove `NewConfigObserver`. I think that is left over from when I was just starting to work on this and wasn't sure the direction to take. All we really use is the target config reconciler for now (I believe)

**Comment by damemi** [comment]
@ingvagabund is this still wip or ready to go soon?

**Comment by ingvagabund** [comment]
@damemi ready!!!

```
$ oc logs -n openshift-kube-descheduler-operator cluster-597cfb8f6b-qmz2c
I0327 16:01:38.239925       1 reflector.go:153] Starting reflector *v1.Node (1h0m0s) from sigs.k8s.io/descheduler/pkg/descheduler/node/node.go:84
I0327 16:01:38.240081       1 reflector.go:188] Listing and watching *v1.Node from sigs.k8s.io/descheduler/pkg/descheduler/node/node.go:84
I0327 16:01:38.339624       1 duplicates.go:49] Processing node: "ip-10-0-157-41.us-east-2.compute.internal"
I0327 16:01:38.444505       1 duplicates.go:49] Processing node: "ip-10-0-161-52.us-east-2.compute.internal"
I0327 16:01:38.545213       1 duplicates.go:49] Processing node: "ip-10-0-174-170.us-east-2.compute.internal"
I0327 16:01:38.643233       1 duplicates.go:49] Processing node: "ip-10-0-131-83.us-east-2.compute.internal"
I0327 16:01:38.768217       1 duplicates.go:49] Processing node: "ip-10-0-140-224.us-east-2.compute.internal"
I0327 16:01:38.860924       1 duplicates.go:49] Processing node: "ip-10-0-146-132.us-east-2.compute.internal"
I0327 16:01:39.357569       1 lownodeutilization.go:145] Node "ip-10-0-140-224.us-east-2.compute.internal" is over utilized with usage: api.ResourceThresholds{"cpu":80.13333333333334, "memory":36.618721049786416, "pods":4.8}
I0327 16:01:39.357616       1 lownodeutilization.go:150] allPods:12, nonRemovablePods:12, bePods:0, bPods:0, gPods:0
I0327 16:01:39.357732       1 lownodeutilization.go:145] Node "ip-10-0-146-132.us-east-2.compute.internal" is over utilized with usage: api.ResourceThresholds{"cpu":85.46666666666667, "memory":44.05371887686421, "pods":7.6}
I0327 16:01:39.357761       1 lownodeutilization.go:150] allPods:19, nonRemovablePods:14, bePods:1, bPods:4, gPods:0
I0327 16:01:39.357932       1 lownodeutilization.go:145] Node "ip-10-0-157-41.us-east-2.compute.internal" is over utilized with usage: api.ResourceThresholds{"cpu":48.628571428571426, "memory":28.83790522680958, "pods":11.2}
I0327 16:01:39.357958       1 lownodeutilization.go:150] allPods:28, nonRemovablePods:27, bePods:0, bPods:1, gPods:0
I0327 16:01:39.358136       1 lownodeutilization.go:145] Node "ip-10-0-161-52.us-east-2.compute.internal" is over utilized with usage: api.ResourceThresholds{"cpu":52.05714285714286, "memory":33.10105217442801, "pods":14.8}
I0327 16:01:39.358159       1 lownodeutilization.go:150] allPods:37, nonRemovablePods:37, bePods:0, bPods:0, gPods:0
I0327 16:01:39.358232       1 lownodeutilization.go:145] Node "ip-10-0-174-170.us-east-2.compute.internal" is over utilized with usage: api.ResourceThresholds{"cpu":93.46666666666667, "memory":41.44871220046829, "pods":5.2}
I0327 16:01:39.358257       1 lownodeutilization.go:150] allPods:13, nonRemovablePods:13, bePods:0, bPods:0, gPods:0
I0327 16:01:39.358408       1 lownodeutilization.go:145] Node "ip-10-0-131-83.us-east-2.compute.internal" is over utilized with usage: api.ResourceThresholds{"cpu":51.48571428571429, "memory":28.837890629943065, "pods":12.8}
I0327 16:01:39.358431       1 lownodeutilization.go:150] allPods:32, nonRemovablePods:31, bePods:0, bPods:1, gPods:0
I0327 16:01:39.358441       1 lownodeutilization.go:66] Criteria for a node under utilization: CPU: 10, Mem: 20, Pods: 30
I0327 16:01:39.358452       1 lownodeutilization.go:70] No node is underutilized, nothing to do here, you might tune your thresholds further
```

```
$ oc get pods -n openshift-kube-descheduler-operator
NAME                                    READY   STATUS    RESTARTS   AGE
cluster-597cfb8f6b-qmz2c                1/1     Running   0          4m11s
descheduler-operator-77dfc57685-tt5lx   1/1     Running   0          4m24s
```

```
$ oc get pods -n openshift-kube-descheduler-operator descheduler-operator-77dfc57685-tt5lx -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.128.2.24"
          ],
          "dns": {},
          "default-route": [
              "10.128.2.1"
          ]
      }]
    openshift.io/scc: restricted
  creationTimestamp: "2020-03-27T16:01:02Z"
  generateName: descheduler-operator-77dfc57685-
  labels:
    name: descheduler-operator
    pod-template-hash: 77dfc57685
  name: descheduler-operator-77dfc57685-tt5lx
  namespace: openshift-kube-descheduler-operator
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: descheduler-operator-77dfc57685
    uid: 14d1e72f-0cf3-46d9-a5fc-17bde8268375
  resourceVersion: "65874"
  selfLink: /api/v1/namespaces/openshift-kube-descheduler-operator/pods/descheduler-operator-77dfc57685-tt5lx
  uid: e96530f7-3e71-4226-81dc-73e025e89c96
spec:
  containers:
  - args:
    - operator
    command:
    - cluster-kube-descheduler-operator
    env:
    - name: WATCH_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: OPERATOR_NAME
      value: descheduler-operator
    image: quay.io/jchaloup/cluster-kube-descheduler-operator:20200327-fixgoroutine
    imagePullPolicy: Always
    name: descheduler-operator
    ports:
    - containerPort: 60000
      name: metrics
      protocol: TCP
    resources: {}
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000550000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: openshift-descheduler-token-6t9xl
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: openshift-descheduler-dockercfg-8wznj
  nodeName: ip-10-0-146-132.us-east-2.compute.internal
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000550000
    seLinuxOptions:
      level: s0:c23,c22
  serviceAccount: openshift-descheduler
  serviceAccountName: openshift-descheduler
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: openshift-descheduler-token-6t9xl
    secret:
      defaultMode: 420
      secretName: openshift-descheduler-token-6t9xl
status:
   ...
```

**Comment by damemi** [comment]
/lgtm
Thanks @ingvagabund for getting this together. Do you want to follow up with a small bump to `v0.18.0` GA tag?

**Pull request merged**
