### PR TITLE
bump k8s to 1.23

### PR DESCRIPTION
**Pull request by atiratree**
Depends on these bumps:
- [x]  openshift/api#1076
- [x] openshift/client-go#203
- [x] openshift/library-go#1259

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
/approve
pending merge of bumps

**Comment by ingvagabund** [comment]
Again, we have not e2e for verifying this actually works. Only that it builds.

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
