### PR TITLE
Fix readme inconsistencies

### LINKED ISSUE #74: README inconsistencies
In testing the operator, found two minor inconsistencies from the README file.

1. The README references the `openshift-descheduler-operator` namespace twice, but it's actually the `openshift-kube-descheduler-operator` namespace.
2. The Sample CR section says that the operator expects the name `config`, but the name is `cluster` when created.

### PR DESCRIPTION
**Pull request by damemi**
Fixes https://github.com/openshift/cluster-kube-descheduler-operator/issues/74

### CODE REVIEW

**Comment by ingvagabund** [comment]
/lgtm
Feel free to push more changes if you find any. I will re-lgtm if needed.

**Comment by bergerhoffer** [comment]
Thanks @damemi! There is one more place that needs updated. I couldn't comment inline on it, but line 52 says "the operator expects `config` CR ...". That should be `cluster`.

**Comment by damemi** [comment]
@bergerhoffer thanks! Fixed

**Comment by szymonhwheels-cloud** [comment]
> Fixes #74

**Pull request merged**
