### PR TITLE
Bug 1989720: Update CRD to accept PodLifetime as duration

### PR DESCRIPTION
**Pull request by damemi**
Switch to `metav1.Duration` so that this gets generated as a `string` validator, and add an additional requirement for `format: duration`

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
/cc @soltysh @kasturinarra

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by damemi** [comment]
@soltysh could you re-tag please?

**Pull request merged**
