### PR TITLE
Bug 1874612: Add operatorhub icon to 4.4 manifest

### PR DESCRIPTION
**Pull request by damemi**

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/retest

**Comment by damemi** [comment]
@ingvagabund any reason for the hold on this now?

**Comment by ingvagabund** [comment]
@damemi icon changed https://github.com/openshift/cluster-kube-descheduler-operator/blob/master/manifests/4.6/cluster-kube-descheduler-operator.v4.6.0.clusterserviceversion.yaml#L78-L80. The PR needs to be updated.

**Comment by damemi** [comment]
@ingvagabund sorry, forgot about this... updated the icon, could you please double-check that I pasted it correctly and re-tag if so? Thanks!

**Pull request merged**
